apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: config
spec:
  rules:
  - host: api.k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: apigw
          servicePort: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: apigw
spec:
  type: ClusterIP
  selector:
    app: spring-cloud-zuul
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-zuul
  labels:
    app: spring-cloud-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-zuul
  template:
    metadata:
      labels:
        app: spring-cloud-zuul
        version: latest
    spec:
      hostname: spring-cloud-zuul
      subdomain: spring-cloud-zuul
      containers:
      - name: spring-cloud-zuul
        image: hubtea/spring-cloud-zuul:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        ports:
        - name: http
          containerPort: 8080